<?php
// Exit if accessed directly.
if (!defined('ABSPATH')) exit;

/**
 * Class DLDC_Settings_Page
 *
 * This class contains repetitive functions that
 * are used globally within the settings.
 *
 * @package		DLDC
 * @subpackage	Classes/DLDC_Settings_Page
 * @author		Mohamed Yassin
 * @since		1.0.0
 * 
 *
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class DLDC_Settings_Page
{
	private $dldc_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'dldc_add_settings_page' ) );
		add_action( 'admin_init', array( $this, 'dldc_page_init' ) );
	}

	public function dldc_add_settings_page() {
		add_menu_page(
			'Comments L&D', // page_title
			'Comments L&D', // menu_title
			'manage_options', // capability
			'dldc', // menu_slug
			array( $this, 'dldc_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);
	}

	public function dldc_create_admin_page() {
		$this->dldc_options = get_option( 'dldc_options' ); ?>

		<div class="wrap">
			<h2>Comments L&D</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'dldc_option_group' );
					do_settings_sections( 'dldc-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function dldc_page_init() {
		register_setting(
			'dldc_option_group', // option_group
			'dldc_options', // option_name
			array( $this, 'dldc_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'dldc_setting_section', // id
			'Settings', // title
			array( $this, 'dldc_section_info' ), // callback
			'dldc-admin' // page
		);

		add_settings_field(
			'display_mode', // id
			'Display Mode', // title
			array( $this, 'display_mode_callback' ), // callback
			'dldc-admin', // page
			'dldc_setting_section' // section
		);

		add_settings_field(
			'restrictions', // id
			'Restrictions', // title
			array( $this, 'restrictions_callback' ), // callback
			'dldc-admin', // page
			'dldc_setting_section' // section
		);

		add_settings_field(
			'display_the_counters', // id
			'Display The Counters ', // title
			array( $this, 'display_the_counters_callback' ), // callback
			'dldc-admin', // page
			'dldc_setting_section' // section
		);
	}

	public function dldc_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['display_mode'] ) ) {
			$sanitary_values['display_mode'] = $input['display_mode'];
		}

		if ( isset( $input['restrictions'] ) ) {
			$sanitary_values['restrictions'] = $input['restrictions'];
		}

		if ( isset( $input['display_the_counters'] ) ) {
			$sanitary_values['display_the_counters'] = $input['display_the_counters'];
		}

		return $sanitary_values;
	}

	public function dldc_section_info() {
		
	}

	public function display_mode_callback() {
		?> <select name="dldc_options[display_mode]" id="display_mode">
			<?php $selected = (isset( $this->dldc_options['display_mode'] ) && $this->dldc_options['display_mode'] === '1') ? 'selected' : '' ; ?>
			<option value="1" <?php echo $selected; ?>>like only</option>
			<?php $selected = (isset( $this->dldc_options['display_mode'] ) && $this->dldc_options['display_mode'] === '2') ? 'selected' : '' ; ?>
			<option value="2" <?php echo $selected; ?>>dislike only</option>
			<?php $selected = (isset( $this->dldc_options['display_mode'] ) && $this->dldc_options['display_mode'] === '3') ? 'selected' : '' ; ?>
			<option value="3" <?php echo $selected; ?>>display both</option>
		</select> <?php
	}

	public function restrictions_callback() {
		?> <select name="dldc_options[restrictions]" id="restrictions">
			<?php $selected = (isset( $this->dldc_options['restrictions'] ) && $this->dldc_options['restrictions'] === '0') ? 'selected' : '' ; ?>
			<option value="0" <?php echo $selected; ?>>All Users</option>
			<?php $selected = (isset( $this->dldc_options['restrictions'] ) && $this->dldc_options['restrictions'] === '1') ? 'selected' : '' ; ?>
			<option value="1" <?php echo $selected; ?>>Logged in User Only</option>
		</select> <?php
	}

	public function display_the_counters_callback() {
		?> <select name="dldc_options[display_the_counters]" id="display_the_counters">
			<?php $selected = (isset( $this->dldc_options['display_the_counters'] ) && $this->dldc_options['display_the_counters'] === '1') ? 'selected' : '' ; ?>
			<option value="1" <?php echo $selected; ?>>like only</option>
			<?php $selected = (isset( $this->dldc_options['display_the_counters'] ) && $this->dldc_options['display_the_counters'] === '2') ? 'selected' : '' ; ?>
			<option value="2" <?php echo $selected; ?>>dislike only</option>
			<?php $selected = (isset( $this->dldc_options['display_the_counters'] ) && $this->dldc_options['display_the_counters'] === '3') ? 'selected' : '' ; ?>
			<option value="3" <?php echo $selected; ?>>display both</option>
		</select> <?php
	}
}